#include <stdio.h>
#include "header.h"

void viewVoterRequest()
{

    struct Request request;
    int currentuserId;
    FILE *approvedrequest = fopen("ApprovedUserFile.csv", "r");
    if (approvedrequest == NULL)
    {
        perror("Error in file opening\n");
    }
    else
    {
        while (fread(&request, sizeof(request), 1, approvedrequest))
        {
            int sec=0;
            clock_t stopclock = CLOCKS_PER_SEC;
            currentuserId = request.UserId;
            printf("Voter with UserId %d has requested for VoterId \n", request.UserId);
            printf("VoterId is being AutoGenerated Please wait");
            while (sec<4)
            {
               if(clock()>stopclock)
               {
                stopclock+=1000000;
                printf(".");
                fflush(stdout);
                sec++;
               }
            }
            
            generateVoterId(currentuserId);
        }
    }
}
void generateVoterId(int userId)
{
    struct User newUser;
    int currentUserId = userId;
    FILE *user = fopen("UserDetails.csv", "r+");
    if (user == NULL)
    {
        perror("Error in file opening\n");
    }
    else
    {
        int month[12] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        char week[7][10];
        char VoterId[20];

        char stringDay[10];
        char stringMonth[10];
        char stringYear[10];

        int day, mon, year, i, r, s = 0, sumMon, sumDay, sumYear;

        strcpy(week[0], "Sunday");
        strcpy(week[1], "Monday");
        strcpy(week[2], "Tuesday");
        strcpy(week[3], "Wednesday");
        strcpy(week[4], "Thursday");
        strcpy(week[5], "Friday");
        strcpy(week[6], "Saturday");

        while (fread(&newUser, sizeof(newUser), 1, user))
        {
            if (newUser.UserId == currentUserId)
            {
                day = newUser.day;
                mon = newUser.mon;
                year = newUser.year;
                if ((year % 400 == 0) || ((year % 4 == 0) && (year % 100 != 0)))
                    month[1] = 29;
                for (i = 0; i < mon - 1; i++)
                    s = s + month[i];
                s = s + (day + year + (year / 4) - 2);
                s = s % 7;

                VoterId[0] = newUser.firstname[0];
                VoterId[1] = newUser.lastname[0];
                VoterId[2] = week[s][0];
                VoterId[3] = strlen(newUser.firstname) + '0';
                VoterId[4] = strlen(newUser.lastname) + '0';
                VoterId[5]='\0';

                sumMon = mon % 10 + ((mon / 10) % 10);
                sprintf(stringMonth, "%d", sumMon);

                sumDay = day % 10 + ((day / 10) % 10);
                sprintf(stringDay, "%d", sumDay);

                while (year > 0)
                {
                    int m = year % 10;
                    sumYear = sumYear + m;
                    year = year / 10;
                }
                sprintf(stringYear, "%d", sumYear);

            strcat(VoterId, stringMonth);
            strcat(VoterId, stringDay);
            strcat(VoterId, stringYear);

            strcpy(newUser.VoterId,VoterId);
            printf("\nVoterId = %s", VoterId);
            
            fseek(user,-sizeof(newUser),SEEK_CUR);
            fwrite(&newUser,sizeof(newUser),1,user);
        }
    }
}
}

void officerMenu()
{
    struct Officer officer;

    char username1[50];
    char password1[50];
    int choice = 0;

    char ch[10];

    strcpy(officer.username, "officer");
    strcpy(officer.password, "1234");

    printf("\nEnter the Username: ");
    scanf("%s", username1);

    printf("\nEnter the password: ");
    scanf("%s", password1);

    if (strcmp(officer.username, username1) == 0 && strcmp(officer.password, password1) == 0)
    {
        while (choice != 2)
    {
        printf("\n---------------------------------------------------------|\n");
        printf("     \033[0;32m  Electronic Voting Machine\033[0;32m                      \033[0;36m|\033[0;37m\n");
        printf("---------------------------------------------------------|\n");
        printf("Please select an option:  ");
        printf("\n1.View Voter Request");
        printf("\n2.Exit");
        printf("\n");
        printf(" Enter The Choice: ");

        // scanf("%d", &choice1);

        scanf("%s", ch);
        choice = atoi(ch);
        switch (choice)
        {
        case 1:
            viewVoterRequest();
            break;
        case 2:
            break;

        default:
            printf("\033[0;31m\n");
            printf(" Invalid Data Enterd Please Enter Valid choise !!! \n");
            printf("\033[0;37m\n");
        }
    }
    }
    else
    {
        printf("\nInvalid username or password");
    }


    
}
