
cc = gcc

target = a.out

$(target): main.o admin.o electoralOfficer.o User.o function.o userCredentials.o
	$(cc)  main.o admin.o electoralOfficer.o User.o function.o userCredentials.o -o $(target)

main.o:main.c  header/header.h
	$(cc) -c main.c

admin.o:source/admin.c   header/header.h
	$(cc) -c source/admin.c

electoralOfficer.o:source/electoralOfficer.c   header/header.h
	$(cc) -c source/electoralOfficer.c

User.o:source/User.c   header/header.h
	$(cc) -c source/User.c

function.o:source/function.c   header/header.h
	$(cc) -c source/function.c
	
userCredentials.o:source/userCredentials.c   header/header.h
	$(cc) -c source/userCredentials.c

clean:
	rm -f $(target)
